version: '3.4'

services:
  server:
    container_name: 'backend'
    command: bash -c 'npm run dev'
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
       - .:/opt/app/server:delegated
       - server_node_modules:/opt/app/server/node_modules
    environment:
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT:-4001}:${SERVER_PORT:-4001}
  client:
    container_name: client
    command: bash -c 'npm run start'
    build: 
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - .:/opt/app/client:delegated
      - client_node_modules:/opt/app/client/node_modules
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT:-4000}:${PORT:-4000}

volumes:
  client_node_modules:
  server_node_modules:
    driver: local