version: '3.4'

services:
  server:
    container_name: 'backend'
    command: bash -c 'npm run dev'
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
       - .:/opt/app/server:delegated
       - server_node_modules:/opt/app/server/node_modules
    env_file:
      - ./server/.env
    ports:
      - ${PORT}:4000

volumes:
  server_node_modules:
    driver: local